// <auto-generated />
namespace LibraryManagementSystem_MVC.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class updatevaidtion : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updatevaidtion));
        
        string IMigrationMetadata.Id
        {
            get { return "202001040658044_update-vaidtion"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
